name: Ruby Testing Workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0' # or the version of Ruby you want to use

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run tests
      run: ruby -Ilib:test *_test.rb
